/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rekammedis;

import javax.swing.JOptionPane;

/**
 *
 * @author andryderr
 */
public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdmin
     */
    koneksi con;

    public HomeAdmin() {
        initComponents();
        con = new koneksi();
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        panelData.setVisible(false);
        panelUser.setLocation(panelUser.getX() - 40, panelUser.getY());
        panelUser.setVisible(false);
        panelLaporan.setLocation(panelLaporan.getX() - 90, panelLaporan.getY());
        panelLaporan.setVisible(false);
        main.setVisible(false);
        settingComponent(0);
    }

    int noMenu = 0;
    int simpanButton = 0;

    public void menu(int i) {
        String query = "";
        switch (i) {
            case 1:
                query = "SELECT t.idTransaksi,t.idRekamMedis,r.namaLengkap,u.namaUser,p.namaPeminjam,t.tglPeminjaman FROM `transaksi` t join rekam_medis r on t.idRekamMedis = r.idRekamMedis join user u on t.idUser = u.idUser join peminjam p on t.idPeminjam=p.idPeminjam";
                break;
            case 2:
                query = "SELECT t.idTransaksi,t.idRekamMedis,r.namaLengkap,u.namaUser,p.namaPeminjam,t.tglPengembalian FROM `transaksi` t join rekam_medis r on t.idRekamMedis = r.idRekamMedis join user u on t.idUser = u.idUser join peminjam p on t.idPeminjam=p.idPeminjam";
                break;
            case 3:
                query = "SELECT t.idTransaksi,t.idRekamMedis,r.namaLengkap,u.namaUser,p.namaPeminjam,t.tglPeminjaman,t.tglPengembalian FROM `transaksi` t join rekam_medis r on t.idRekamMedis = r.idRekamMedis join user u on t.idUser = u.idUser join peminjam p on t.idPeminjam=p.idPeminjam";
                break;
            case 4:
                query = "SELECT t.idTransaksi,t.idRekamMedis,r.namaLengkap,u.namaUser,p.namaPeminjam,t.tglPeminjaman,t.tglPengembalian FROM `transaksi` t join rekam_medis r on t.idRekamMedis = r.idRekamMedis join user u on t.idUser = u.idUser join peminjam p on t.idPeminjam=p.idPeminjam";
                break;
            case 5:
                query = "select * from user where jabatan = 1";
                break;
            case 6:
                query = "select * from user where jabatan = 3";
                break;
            case 7:
                query = "SELECT t.idTransaksi,t.idRekamMedis,r.namaLengkap,u.namaUser,p.namaPeminjam,t.tglPeminjaman FROM `transaksi` t join rekam_medis r on t.idRekamMedis = r.idRekamMedis join user u on t.idUser = u.idUser join peminjam p on t.idPeminjam=p.idPeminjam";
                break;
            case 8:
                query = "SELECT t.idTransaksi,t.idRekamMedis,r.namaLengkap,u.namaUser,p.namaPeminjam,t.tglPengembalian FROM `transaksi` t join rekam_medis r on t.idRekamMedis = r.idRekamMedis join user u on t.idUser = u.idUser join peminjam p on t.idPeminjam=p.idPeminjam";
                break;
            case 9:
                query = "SELECT t.idTransaksi,t.idRekamMedis,r.namaLengkap,u.namaUser,p.namaPeminjam,t.tglPeminjaman,t.tglPengembalian FROM `transaksi` t join rekam_medis r on t.idRekamMedis = r.idRekamMedis join user u on t.idUser = u.idUser join peminjam p on t.idPeminjam=p.idPeminjam";
                break;
            default:
                throw new AssertionError();
        }
        tabelMain.setModel(con.select(query));
        button(simpanButton);
        noMenu = i;
        settingComponent(i);
    }
    
    public void settingComponent(int i){
        switch (i) {
            case 0:
                panelHome.setVisible(true);
                main.setVisible(false);
                break;
            case 1:
                panelHome.setVisible(false);
                main.setVisible(true);
                panelDataUser.setVisible(false);
                createNew.setVisible(false);
                updateData.setVisible(false);
                deleteData.setVisible(false);
                break;
            default:
                throw new AssertionError();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        data = new javax.swing.JButton();
        user = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        panelData = new javax.swing.JPanel();
        btnDataPeminjaman = new javax.swing.JButton();
        btnDataPengembalian = new javax.swing.JButton();
        btnDataKeterlambatanRM = new javax.swing.JButton();
        btnDataTiapUnit = new javax.swing.JButton();
        panelUser = new javax.swing.JPanel();
        btnPetugasFilling = new javax.swing.JButton();
        btnPetugasTPP = new javax.swing.JButton();
        panelLaporan = new javax.swing.JPanel();
        btnLaporanPeminjaman = new javax.swing.JButton();
        btnLaporanPengembalian = new javax.swing.JButton();
        btnLaporanPenyimpanan = new javax.swing.JButton();
        main = new javax.swing.JPanel();
        panelDataUser = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        namaPegawai = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        submitUser = new javax.swing.JButton();
        cancelUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMain = new javax.swing.JTable();
        createNew = new javax.swing.JButton();
        updateData = new javax.swing.JButton();
        deleteData = new javax.swing.JButton();
        panelHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        angkaPeminjaman = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        angkaPengembalian = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        angkaKeterlambatan = new javax.swing.JLabel();

        javax.swing.GroupLayout search1Layout = new javax.swing.GroupLayout(search1);
        search1.setLayout(search1Layout);
        search1Layout.setHorizontalGroup(
            search1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );
        search1Layout.setVerticalGroup(
            search1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Home Admin Kepala Rekam Medis | SI - RM");

        home.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        home.setText("HOME");
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        data.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        data.setText("DATA EKSPEDISI");
        data.setContentAreaFilled(false);
        data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });

        user.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        user.setText("USER");
        user.setContentAreaFilled(false);
        user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        laporan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        laporan.setText("LAPORAN");
        laporan.setContentAreaFilled(false);
        laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 103);

        panelData.setBackground(new java.awt.Color(255, 255, 255));
        panelData.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)), null));

        btnDataPeminjaman.setBackground(new java.awt.Color(255, 255, 255));
        btnDataPeminjaman.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDataPeminjaman.setText("Data Peminjaman");
        btnDataPeminjaman.setContentAreaFilled(false);
        btnDataPeminjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataPeminjamanActionPerformed(evt);
            }
        });

        btnDataPengembalian.setBackground(new java.awt.Color(255, 255, 255));
        btnDataPengembalian.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDataPengembalian.setText("Data Pengembalian");
        btnDataPengembalian.setContentAreaFilled(false);
        btnDataPengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataPengembalianActionPerformed(evt);
            }
        });

        btnDataKeterlambatanRM.setBackground(new java.awt.Color(255, 255, 255));
        btnDataKeterlambatanRM.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDataKeterlambatanRM.setText("Data Keterlambatan RM");
        btnDataKeterlambatanRM.setContentAreaFilled(false);
        btnDataKeterlambatanRM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataKeterlambatanRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataKeterlambatanRMActionPerformed(evt);
            }
        });

        btnDataTiapUnit.setBackground(new java.awt.Color(255, 255, 255));
        btnDataTiapUnit.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDataTiapUnit.setText("Data Tiap Unit");
        btnDataTiapUnit.setContentAreaFilled(false);
        btnDataTiapUnit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataTiapUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataTiapUnitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDataLayout = new javax.swing.GroupLayout(panelData);
        panelData.setLayout(panelDataLayout);
        panelDataLayout.setHorizontalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDataPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDataPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDataKeterlambatanRM, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
            .addComponent(btnDataTiapUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDataLayout.setVerticalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDataPeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDataPengembalian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDataKeterlambatanRM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDataTiapUnit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelData);
        panelData.setBounds(131, 109, 194, 150);

        panelUser.setBackground(new java.awt.Color(255, 255, 255));
        panelUser.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)), null));

        btnPetugasFilling.setBackground(new java.awt.Color(255, 255, 255));
        btnPetugasFilling.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnPetugasFilling.setText("Petugas Filling");
        btnPetugasFilling.setContentAreaFilled(false);
        btnPetugasFilling.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPetugasFilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetugasFillingActionPerformed(evt);
            }
        });

        btnPetugasTPP.setBackground(new java.awt.Color(255, 255, 255));
        btnPetugasTPP.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnPetugasTPP.setText("Petugas TPP");
        btnPetugasTPP.setContentAreaFilled(false);
        btnPetugasTPP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPetugasTPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetugasTPPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUserLayout = new javax.swing.GroupLayout(panelUser);
        panelUser.setLayout(panelUserLayout);
        panelUserLayout.setHorizontalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPetugasFilling, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
            .addComponent(btnPetugasTPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelUserLayout.setVerticalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPetugasFilling)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPetugasTPP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelUser);
        panelUser.setBounds(331, 109, 194, 84);

        panelLaporan.setBackground(new java.awt.Color(255, 255, 255));
        panelLaporan.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)), null)));

        btnLaporanPeminjaman.setBackground(new java.awt.Color(255, 255, 255));
        btnLaporanPeminjaman.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnLaporanPeminjaman.setText("Laporan Peminjaman");
        btnLaporanPeminjaman.setContentAreaFilled(false);
        btnLaporanPeminjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporanPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanPeminjamanActionPerformed(evt);
            }
        });

        btnLaporanPengembalian.setBackground(new java.awt.Color(255, 255, 255));
        btnLaporanPengembalian.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnLaporanPengembalian.setText("Laporan Pengembalian");
        btnLaporanPengembalian.setContentAreaFilled(false);
        btnLaporanPengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporanPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanPengembalianActionPerformed(evt);
            }
        });

        btnLaporanPenyimpanan.setBackground(new java.awt.Color(255, 255, 255));
        btnLaporanPenyimpanan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnLaporanPenyimpanan.setText("Laporan Penyimpanan");
        btnLaporanPenyimpanan.setContentAreaFilled(false);
        btnLaporanPenyimpanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporanPenyimpanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanPenyimpananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLaporanLayout = new javax.swing.GroupLayout(panelLaporan);
        panelLaporan.setLayout(panelLaporanLayout);
        panelLaporanLayout.setHorizontalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLaporanPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLaporanPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
            .addComponent(btnLaporanPenyimpanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLaporanLayout.setVerticalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLaporanPeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaporanPengembalian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaporanPenyimpanan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelLaporan);
        panelLaporan.setBounds(530, 110, 194, 117);

        main.setBackground(new java.awt.Color(226, 226, 226));
        main.setLayout(null);

        panelDataUser.setBackground(new java.awt.Color(37, 147, 220));
        panelDataUser.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Pegawai");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(":");

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");

        namaPegawai.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        username.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        password.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        submitUser.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        submitUser.setText("Submit");
        submitUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUserActionPerformed(evt);
            }
        });

        cancelUser.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cancelUser.setText("Cancel");
        cancelUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDataUserLayout = new javax.swing.GroupLayout(panelDataUser);
        panelDataUser.setLayout(panelDataUserLayout);
        panelDataUserLayout.setHorizontalGroup(
            panelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(panelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataUserLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username))
                    .addGroup(panelDataUserLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaPegawai, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                    .addGroup(panelDataUserLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password)
                            .addGroup(panelDataUserLayout.createSequentialGroup()
                                .addComponent(submitUser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelDataUserLayout.setVerticalGroup(
            panelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataUserLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(namaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitUser)
                    .addComponent(cancelUser))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        main.add(panelDataUser);
        panelDataUser.setBounds(10, 60, 410, 220);

        tabelMain.setAutoCreateRowSorter(true);
        tabelMain.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabelMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelMain.setColumnSelectionAllowed(true);
        tabelMain.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelMain.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tabelMain);
        tabelMain.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelMain.getColumnModel().getColumnCount() > 0) {
            tabelMain.getColumnModel().getColumn(0).setResizable(false);
            tabelMain.getColumnModel().getColumn(1).setResizable(false);
            tabelMain.getColumnModel().getColumn(2).setResizable(false);
            tabelMain.getColumnModel().getColumn(3).setResizable(false);
        }

        main.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 1350, 550);

        createNew.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        createNew.setText("Create New");
        createNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewActionPerformed(evt);
            }
        });
        main.add(createNew);
        createNew.setBounds(10, 20, 233, 37);

        updateData.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        updateData.setText("Update Data");
        main.add(updateData);
        updateData.setBounds(580, 30, 233, 33);

        deleteData.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        deleteData.setText("Delete Data");
        main.add(deleteData);
        deleteData.setBounds(1130, 20, 233, 33);

        jPanel1.add(main);
        main.setBounds(0, 110, 1370, 640);

        panelHome.setBackground(new java.awt.Color(117, 220, 255));
        panelHome.setEnabled(false);

        jLabel2.setText("[GAMBAR]");

        jPanel3.setBackground(new java.awt.Color(244, 148, 51));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Peminjaman");

        angkaPeminjaman.setFont(new java.awt.Font("Tahoma", 0, 70)); // NOI18N
        angkaPeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        angkaPeminjaman.setText("00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(67, 67, 67))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(angkaPeminjaman)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel4)
                .addGap(101, 101, 101)
                .addComponent(angkaPeminjaman)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(189, 37, 227));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pengembalian");

        angkaPengembalian.setFont(new java.awt.Font("Tahoma", 0, 70)); // NOI18N
        angkaPengembalian.setForeground(new java.awt.Color(255, 255, 255));
        angkaPengembalian.setText("00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(angkaPengembalian)
                        .addGap(101, 101, 101))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel5)
                .addGap(100, 100, 100)
                .addComponent(angkaPengembalian)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(47, 206, 87));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Keterlambatan");

        angkaKeterlambatan.setFont(new java.awt.Font("Tahoma", 0, 70)); // NOI18N
        angkaKeterlambatan.setForeground(new java.awt.Color(255, 255, 255));
        angkaKeterlambatan.setText("00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(angkaKeterlambatan)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(51, 51, 51))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel6)
                .addGap(102, 102, 102)
                .addComponent(angkaKeterlambatan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel2)
                .addGap(227, 227, 227)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelHome);
        panelHome.setBounds(10, 110, 1350, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        button(3);
    }//GEN-LAST:event_laporanActionPerformed
    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        button(1);
    }//GEN-LAST:event_dataActionPerformed

    private void btnLaporanPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanPengembalianActionPerformed
        menu(8);
    }//GEN-LAST:event_btnLaporanPengembalianActionPerformed
    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        button(2);
    }//GEN-LAST:event_userActionPerformed

    private void btnPetugasTPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetugasTPPActionPerformed
        menu(6);
    }//GEN-LAST:event_btnPetugasTPPActionPerformed

    private void btnLaporanPenyimpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanPenyimpananActionPerformed
        menu(9);
    }//GEN-LAST:event_btnLaporanPenyimpananActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        button(4);
    }//GEN-LAST:event_homeActionPerformed

    private void btnDataPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPeminjamanActionPerformed
        menu(1);
    }//GEN-LAST:event_btnDataPeminjamanActionPerformed

    private void btnDataPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPengembalianActionPerformed
        menu(2);
    }//GEN-LAST:event_btnDataPengembalianActionPerformed

    private void btnDataKeterlambatanRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataKeterlambatanRMActionPerformed
        menu(3);
    }//GEN-LAST:event_btnDataKeterlambatanRMActionPerformed

    private void btnDataTiapUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataTiapUnitActionPerformed
        menu(4);
    }//GEN-LAST:event_btnDataTiapUnitActionPerformed

    private void btnPetugasFillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetugasFillingActionPerformed
        menu(5);
    }//GEN-LAST:event_btnPetugasFillingActionPerformed

    private void btnLaporanPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanPeminjamanActionPerformed
        menu(7);
    }//GEN-LAST:event_btnLaporanPeminjamanActionPerformed

    private void cancelUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelUserActionPerformed
        panelDataUser.setVisible(false);
    }//GEN-LAST:event_cancelUserActionPerformed

    private void submitUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUserActionPerformed
        int jabatan;
        if (noMenu == 5) {
            jabatan = 1;
        } else {
            jabatan = 3;
        }
        String query = "INSERT INTO `user`(`namaUser`, `username`, `password`, `jabatan`) VALUES ('" + namaPegawai.getText() + "','" + username.getText() + "','" + password.getText() + "','"+jabatan+"')";
        if (con.insertUpdateDelete(query)) {
            JOptionPane.showMessageDialog(panelHome, "Submit Data was Successfull", "Pemberitahuan",1);
            menu(noMenu);
            namaPegawai.setText("");
            username.setText("");
            password.setText("");
            
        }else{
            JOptionPane.showMessageDialog(panelHome, "Submit Data was Failed", "Pemberitahuan",2);
        }
    }//GEN-LAST:event_submitUserActionPerformed

    private void createNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewActionPerformed
        if (panelDataUser.isVisible()) {
            panelDataUser.setVisible(false);
        }else{
            panelDataUser.setVisible(true);
        }
    }//GEN-LAST:event_createNewActionPerformed

    public void button(int i) {
        if (simpanButton == i) {
            panelData.setVisible(false);
            panelUser.setVisible(false);
            panelLaporan.setVisible(false);
            simpanButton = 0;
        } else {
            switch (i) {
                case 1:
                    panelData.setVisible(true);
                    panelUser.setVisible(false);
                    panelLaporan.setVisible(false);
                    break;
                case 2:
                    panelData.setVisible(false);
                    panelUser.setVisible(true);
                    panelLaporan.setVisible(false);
                    break;
                case 3:
                    panelData.setVisible(false);
                    panelUser.setVisible(false);
                    panelLaporan.setVisible(true);
                    break;
                case 4:
                    panelData.setVisible(false);
                    panelUser.setVisible(false);
                    panelLaporan.setVisible(false);
                    break;
                default:
                    throw new AssertionError();
            }
            simpanButton = i;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel angkaKeterlambatan;
    private javax.swing.JLabel angkaPeminjaman;
    private javax.swing.JLabel angkaPengembalian;
    private javax.swing.JButton btnDataKeterlambatanRM;
    private javax.swing.JButton btnDataPeminjaman;
    private javax.swing.JButton btnDataPengembalian;
    private javax.swing.JButton btnDataTiapUnit;
    private javax.swing.JButton btnLaporanPeminjaman;
    private javax.swing.JButton btnLaporanPengembalian;
    private javax.swing.JButton btnLaporanPenyimpanan;
    private javax.swing.JButton btnPetugasFilling;
    private javax.swing.JButton btnPetugasTPP;
    private javax.swing.JButton cancelUser;
    private javax.swing.JButton createNew;
    private javax.swing.JButton data;
    private javax.swing.JButton deleteData;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton laporan;
    private javax.swing.JPanel main;
    private javax.swing.JTextField namaPegawai;
    private javax.swing.JPanel panelData;
    private javax.swing.JPanel panelDataUser;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLaporan;
    private javax.swing.JPanel panelUser;
    private javax.swing.JTextField password;
    private javax.swing.JPanel search1;
    private javax.swing.JButton submitUser;
    private javax.swing.JTable tabelMain;
    private javax.swing.JButton updateData;
    private javax.swing.JButton user;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
